var _lastSearchedTerm = "";

$(document).ready(function(){
	
	enableSearchPlugin();

	moreResults();

});

// sets more results
function moreResults() {


	$('.more-results').click(function(){

		searchForData( _lastSearchedTerm );

	});

}

// enables search
function enableSearchPlugin() {

	$('.search-box').keyup(function(e){

		// on pressing enter key
		if( e.keyCode == 13 && e.shiftKey != true ) {

			$('.fill-data').html('');
			$('.more-results').addClass('hide');

			searchForData(this);
			findTheDuck(this);
		}

		e.preventDefault();

	});

}

// using the DUCK-API
function findTheDuck( elem ) {

	// making the ajax request
	$.ajax({
		type: 'GET',
		url :'http://api.duckduckgo.com/',
		data: {
			q: encodeURIComponent($(elem).val()),
			format: 'json'
		},
		jsonCallback: 'jsonp',
		dataType: 'jsonp',
		success: function(data){

			duckTheData(data);

		}
	});
	

}

// ducking the data - filling it :P
function duckTheData( data ) {

	var exposure = false;

	if( data.Definition )
	{
		$('.define').children('h3').html(data.Heading);
		$('.define').children('p').html(data.Definition);
		$('.define').children('div').children('a').html('Source : '+data.DefinitionSource);
		$('.define').children('div').children('a').attr('src',data.DefinitionURL);
		exposure = true;
	}

	if( !data.AbstractText.match("") )
	{
		$('.abs').children('p').html(data.AbstractText);
		$('.abs').children('div').children('a').html('Source : '+data.AbstractSource);
		$('.abs').children('div').children('a').attr('src',data.AbstractURL);
		exposure = true;
	}

	if( exposure )
		$('.duck-data').removeClass('hide');

}

// search for data using Social-Mention-API
function searchForData( elem ) {

	$(elem).attr('disabled','disabled');
	$('.load-text').removeClass('hide');

	// making the ajax request
	$.ajax({
		type: 'GET',
	    /* -------------------------------------------------------------------------
		 || if you are reading this, I have to say this is the worst API seen ever ||
		 || no option to restrict the number of results generated by the API :(    ||
		  --------------------------------------------------------------------------  */
		url :'http://api2.socialmention.com/search',
		data: {
			q: encodeURIComponent($(elem).val()),
			f: 'jsonp',
			t: 'all'
		},
		jsonCallback: 'jsonp',
		dataType: 'jsonp',
		success: function(data){

			$('.load-text').addClass('hide');
			$('.more-results').removeClass('hide');
			$(elem).removeAttr('disabled');
			$(elem).val('');
			
			onResults(data);
		}
	});

}

// on receving the results
function onResults( data ) {

	for(var i=0;i<data.count;i++) 
		insertNewBox(data.items[i]);

}

// inserts a new box
function insertNewBox( info ) {

	var clone = $('.info-box.hide').clone();

	var title = info.title + (info.title.length > 200 ? '...' : '');

	if( info.user_image )
		$(clone).children('.text-user').children('.profile').attr('src',info.user_image);
	else
		$(clone).children('.text-user').children('.profile').remove();

	if( info.user )
		$(clone).children('.text-user').children('a').html(info.user);
	else
		$(clone).children('.text-user').remove();

	if( info.user )		
		$(clone).children('.text-user').children('a').html(info.user);
	else
		$(clone).children('.text-user').children('a').remove();

	if( info.user_link )
		$(clone).children('.text-user').children('a').attr('href',info.user_link);
	else
		$(clone).children('.text-user').children('a').remove();

	$(clone).children('.text-desc').html(info.title);
	
	if( info.image )
		$(clone).children('.embedded').children('img').attr('src',info.image);
	else
		$(clone).children('.embedded').remove();

	if( info.timestamp ){
		$(clone).children('.url').children('.timestamp').html(new Date(info.timestamp).toISOString());
		$(clone).children('.url').children('.timestamp').attr('title',new Date(info.timestamp).toISOString());
	}
	else
		$(clone).children('.url').children('.timestamp').remove();


	$(clone).children('.url').children('a').attr('href',info.link);
	$(clone).children('.url').children('.favicon').attr('src',info.favicon);
	$(clone).children('.url').append(info.source);


	$(clone).removeClass('hide');

	$('.fill-data').append(clone);

	$('.timestamp').timeago();

}


